# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'maskargo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for maskargo
  pod 'Alamofire'
  pod 'Spring', :git => 'https://github.com/MengTo/Spring.git'
  pod 'Kingfisher', '~> 4.0'
  pod 'Hero'
  pod 'SnapKit', '~> 4.0.0'
  pod 'AudioKit', '~> 4.0'
  pod "ViewAnimator"

end
